In [1]:
# Exercise: Generation and Manipulation of Numpy Arrays

import numpy as np

# Create a 3x3x3 array with random values
array_3x3x3 = np.random.random((3, 3, 3))
print("3x3x3 array with random values:\n", array_3x3x3)


3x3x3 array with random values:
 [[[0.56512562 0.37690822 0.36335043]
  [0.09170674 0.431468   0.49550865]
  [0.59381577 0.69071516 0.46555168]]

 [[0.86766232 0.69371573 0.03389919]
  [0.55347381 0.6176104  0.5589689 ]
  [0.91561348 0.83360141 0.89213807]]

 [[0.6255666  0.04746589 0.50342827]
  [0.80833018 0.36562987 0.69917004]
  [0.29988566 0.14856413 0.11692126]]]


In [2]:
# Create a 10x10 array with random values

array_10x10 = np.random.random((10, 10))
min_val = array_10x10.min()
max_val = array_10x10.max()
print("10x10 array with random values:\n", array_10x10)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


10x10 array with random values:
 [[2.67985260e-01 6.62966319e-01 6.55616465e-01 9.64954559e-01
  3.58283578e-01 8.55648619e-01 1.59825390e-01 5.21566015e-01
  5.04279761e-01 5.47090337e-01]
 [4.90989478e-01 1.13108211e-01 8.81206152e-01 8.37295810e-01
  1.49975690e-01 5.17565134e-01 5.83364753e-01 8.54598714e-01
  2.06281855e-01 6.17255495e-01]
 [4.06872775e-01 4.53966329e-01 2.28137041e-01 3.55015711e-01
  9.46731591e-01 1.39131301e-01 9.44876268e-01 4.31828719e-01
  8.46079069e-01 6.48909901e-01]
 [6.57141931e-01 4.29622187e-01 2.37373795e-01 8.28402682e-01
  1.12005839e-01 2.00437393e-01 9.16168446e-01 9.42254101e-03
  6.43905757e-01 9.86405497e-01]
 [9.21489485e-01 1.00742210e-01 2.31925634e-01 2.34857244e-01
  1.64962920e-01 1.92157402e-01 4.68584898e-01 6.20978638e-01
  8.69938304e-01 2.47239638e-01]
 [6.93727644e-01 6.21359848e-01 9.76367924e-01 8.11497511e-02
  7.95526392e-01 5.64750756e-01 5.02389945e-01 2.06594063e-02
  1.65990152e-01 9.54845486e-01]
 [6.25279218e-01 4.097596

In [3]:
# Create a random vector of size 30

vector_30 = np.random.random(30)
mean_val = vector_30.mean()
print("Random vector of size 30:\n", vector_30)
print("Mean value:", mean_val)


Random vector of size 30:
 [0.2443192  0.50460279 0.69850903 0.07561504 0.78082238 0.25945313
 0.12251375 0.72312535 0.28500296 0.14242545 0.83396565 0.70564034
 0.65724247 0.51980066 0.47837306 0.66077767 0.59603285 0.9294037
 0.38774623 0.05728808 0.29632698 0.84813997 0.30694087 0.73915983
 0.88118416 0.61862453 0.83453006 0.20199172 0.44680969 0.1351096 ]
Mean value: 0.49904924013154134


In [4]:
# Create a 2D array with 1 on the border and 0 inside

array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print("2D array with border of 1 and inside 0:\n", array_2d)


2D array with border of 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# Create a 2D array with 1 on the border and 0 inside

array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print("2D array with border of 1 and inside 0:\n", array_2d)


2D array with border of 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# Add a border around an existing array

existing_array = np.ones((3, 3))
padded_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("Array with added border:\n", padded_array)


Array with added border:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# Replace all odd numbers in an array with -1

original_array = np.array([0, 1, 2, 3, 4, 5])
modified_array = np.where(original_array % 2 == 1, -1, original_array)
print("Original array:", original_array)
print("Modified array:", modified_array)


Original array: [0 1 2 3 4 5]
Modified array: [ 0 -1  2 -1  4 -1]


In [8]:
# Create a 5x5 matrix with specific diagonal values

diagonal_matrix = np.diag([1, 2, 3, 4, 7])
print("5x5 matrix with diagonal values:\n", diagonal_matrix)


5x5 matrix with diagonal values:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 7]]


In [10]:
# Create an 8x8 matrix with a checkerboard pattern

checkerboard_matrix = np.zeros((8, 8))
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("8x8 checkerboard matrix:\n", checkerboard_matrix)


8x8 checkerboard matrix:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [11]:
# Find the index of the 100th element in a (6,7,8) shape array

index_100th_element = np.unravel_index(100, (6, 7, 8))
print("Index of the 100th element in a (6, 7, 8) array:", index_100th_element)


Index of the 100th element in a (6, 7, 8) array: (1, 5, 4)


In [13]:
# Normalize a 5x5 random matrix

random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print("Normalized 5x5 matrix:\n", normalized_matrix)


Normalized 5x5 matrix:
 [[0.10658433 0.18253283 0.44267797 0.74821395 0.31079653]
 [0.71891961 0.99145649 0.82899527 0.48105712 0.38766824]
 [0.15915584 0.48740628 0.33546278 0.         0.25036193]
 [0.96395283 1.         0.80505096 0.50998589 0.98543711]
 [0.32670632 0.51257452 0.87726006 0.44819973 0.91435252]]


In [12]:
# Extract unique rows from a 2D array

array_2d = np.array([[1, 2, 3], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
unique_rows = np.unique(array_2d, axis=0)
print("Unique rows from the 2D array:\n", unique_rows)


Unique rows from the 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Create a structured array with custom dtype

dtype = np.dtype([('position', float, (2,)), ('color', float, (3,))])
structured_array = np.array([((1, 2), (255, 0, 0)), ((4, 5), (0, 255, 0))], dtype=dtype)
print("Structured array:\n", structured_array)


Structured array:
 [([1., 2.], [255.,   0.,   0.]) ([4., 5.], [  0., 255.,   0.])]


In [15]:
# Accumulate elements of a vector based on an index list

X = [1, 2, 3, 4, 5, 6]
I = [0, 1, 2, 0, 1, 2]
F = np.zeros(3)
np.add.at(F, I, X)
print("Accumulated array F:", F)


Accumulated array F: [5. 7. 9.]


In [16]:
# Sum over the last two axes of a four-dimensional array

array_4d = np.random.random((3, 4, 5, 6))
sum_over_axes = np.sum(array_4d, axis=(-2, -1))
print("Sum over the last two axes:\n", sum_over_axes)


Sum over the last two axes:
 [[15.78133529 13.315471   14.5878325  14.59832701]
 [15.3643771  15.78163944 13.57879419 12.90794261]
 [13.53529757 15.27084509 13.60413555 12.52242167]]


In [17]:
# Get the diagonal of a dot product

A = np.random.random((5, 5))
B = np.random.random((5, 5))
dot_product = np.dot(A, B)
diagonal = np.diag(dot_product)
print("Diagonal of the dot product:\n", diagonal)


Diagonal of the dot product:
 [1.33301568 1.661991   1.19983516 0.52658222 1.7492958 ]


In [18]:
# Build a new vector with interleaved zeros

vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) + (len(vector) - 1) * 3)
new_vector[::4] = vector
print("New vector with interleaved zeros:\n", new_vector)


New vector with interleaved zeros:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [19]:
# Compute averages using a sliding window

def sliding_window_mean(arr, window_size):
    cumsum = np.cumsum(np.insert(arr, 0, 0))
    return (cumsum[window_size:] - cumsum[:-window_size]) / window_size

arr = np.arange(1, 11)  # Example array
window_size = 3
averages = sliding_window_mean(arr, window_size)
print("Averages using sliding window:\n", averages)


Averages using sliding window:
 [2. 3. 4. 5. 6. 7. 8. 9.]


In [20]:
# Select rows from a 2D array based on multinomial distribution

X = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 1], [3, 0, 0]])
n = 4
rows = [row for row in X if np.sum(row) == n and np.all(row == np.round(row))]
print("Rows interpreted as draws from a multinomial distribution:\n", rows)


Rows interpreted as draws from a multinomial distribution:
 [array([2, 1, 1]), array([1, 2, 1])]


In [21]:
# Compute bootstrapped 95% confidence intervals

data = np.random.randn(100)  # Example 1D array
N = 1000  # Number of bootstrap samples
means = np.array([np.mean(np.random.choice(data, size=data.size, replace=True)) for _ in range(N)])
conf_interval = np.percentile(means, [2.5, 97.5])
print("95% confidence interval for the mean:", conf_interval)


95% confidence interval for the mean: [-0.17629227  0.21933268]
