In [1]:
# Import the numpy package under the name np

import numpy as np

In [2]:
# Create a vector of zeros with size 10 using np.zeros()

vector_zeros = np.zeros(10)
print("Vector of zeros:", vector_zeros)

Vector of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Compute the memory size of the array

memory_size = vector_zeros.size * vector_zeros.itemsize
print("Memory size of the array:", memory_size)

Memory size of the array: 80


In [ ]:
# Retrieve the documentation of the numpy add function from the command line
# You can do this in a Python environment by typing: np.info(np.add)
# In a Jupyter Notebook, you can use the following:
# ?np.add

In [4]:
# Create a vector with values ranging from 10 to 49 using np.arange()

vector_range = np.arange(10, 50)
print("Vector with values from 10 to 49:", vector_range)

Vector with values from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# Reverse the vector using slicing

reversed_vector = vector_range[::-1]
print("Reversed vector:", reversed_vector)

Reversed vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# Create a 3x3 matrix with values ranging from 0 to 8 using np.reshape()

matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero()

array_nonzero = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(array_nonzero)
print("Indices of non-zero elements:", nonzero_indices)

Indices of non-zero elements: (array([0, 1, 4], dtype=int64),)


In [8]:
# Create a 3x3 identity matrix using np.eye()

identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Create a 5x5 matrix with row values ranging from 0 to 4

matrix_5x5 = np.tile(np.arange(5), (5, 1))
print("5x5 matrix with row values from 0 to 4:\n", matrix_5x5)

5x5 matrix with row values from 0 to 4:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [11]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded, using np.linspace

vector_linspace = np.linspace(0, 1, 12)[1:-1]
print("Vector of size 10 with values from 0 to 1 (excluded):", vector_linspace)

Vector of size 10 with values from 0 to 1 (excluded): [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [9]:
# Create a random vector of size 10 and sort it

random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("Sorted random vector:", sorted_vector)

Sorted random vector: [0.01732503 0.17362741 0.17650931 0.1881937  0.23294879 0.32126551
 0.41144434 0.57291573 0.77877823 0.78817277]


In [12]:
# Print the minimum and maximum representable value for each numpy scalar type (int8, int32, int64, float32, float64)

print("Minimum and maximum values for int8:", np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print("Minimum and maximum values for int32:", np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print("Minimum and maximum values for int64:", np.iinfo(np.int64).min, np.iinfo(np.int64).max)
print("Minimum and maximum values for float32:", np.finfo(np.float32).min, np.finfo(np.float32).max)
print("Minimum and maximum values for float64:", np.finfo(np.float64).min, np.finfo(np.float64).max)


Minimum and maximum values for int8: -128 127
Minimum and maximum values for int32: -2147483648 2147483647
Minimum and maximum values for int64: -9223372036854775808 9223372036854775807
Minimum and maximum values for float32: -3.4028235e+38 3.4028235e+38
Minimum and maximum values for float64: -1.7976931348623157e+308 1.7976931348623157e+308


In [13]:
# Convert a float (32 bits) array into an integer (32 bits) in place using np.ndarray.astype

float_array = np.array([1.5, 2.7, 3.2], dtype=np.float32)
int_array = float_array.astype(np.int32)
print("Converted integer array:", int_array)

Converted integer array: [1 2 3]


In [15]:
# Subtract the mean of each row of a matrix using np.mean with axis=1

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_mean_subtracted = matrix - matrix.mean(axis=1, keepdims=True)
print("Matrix with mean subtracted from each row:\n", row_mean_subtracted)

Matrix with mean subtracted from each row:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [14]:
# Sort an array by the nth column using np.argsort

array_2d = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
sorted_by_nth_col = array_2d[array_2d[:, 1].argsort()]
print("Array sorted by the second column:\n", sorted_by_nth_col)

Array sorted by the second column:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [16]:
# Swap two rows of an array using array indexing

array_to_swap = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
array_to_swap[[0, 1]] = array_to_swap[[1, 0]]
print("Array with first and second rows swapped:\n", array_to_swap)


Array with first and second rows swapped:
 [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [17]:
# Given an array C that is a bincount, produce an array A such that np.bincount(A) == C using np.repeat

C = np.array([4, 3, 0, 1])
A = np.repeat(np.arange(len(C)), C)
print("Array A from bincount C:", A)

Array A from bincount C: [0 0 0 0 1 1 1 3]
