In [1]:
# Exercise: Advanced NumPy Techniques
import numpy as np

# Create a checkerboard 8x8 matrix
checkerboard_matrix = np.tile([[0, 1], [1, 0]], (4, 4))
print("Checkerboard 8x8 matrix:\n", checkerboard_matrix)


Checkerboard 8x8 matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
# Create a 2D array of shape (2,4) with dtype numpy.int16

array_2d_int16 = np.zeros((2, 4), dtype=np.int16)
print("2D array with dtype numpy.int16:\n", array_2d_int16)
print("dtype of the array:", array_2d_int16.dtype)


2D array with dtype numpy.int16:
 [[0 0 0 0]
 [0 0 0 0]]
dtype of the array: int16


In [3]:
# Multiply a 5x3 matrix by a 3x2 matrix

matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
result_matrix = np.dot(matrix_5x3, matrix_3x2)
print("Result of 5x3 multiplied by 3x2:\n", result_matrix)


Result of 5x3 multiplied by 3x2:
 [[0.81194768 0.4633466 ]
 [1.03630849 0.56794244]
 [0.4194388  0.08459034]
 [0.66768112 0.26326861]
 [0.38911425 0.21725946]]


In [4]:
# Negate all elements which are between 3 and 8

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
print("Array with negated elements between 3 and 8:\n", array_1d)


Array with negated elements between 3 and 8:
 [ 1  2  3 -4 -5 -6 -7  8  9]


In [5]:
# Find common values between two arrays

array1 = np.array([1, 2, 3, 4])
array2 = np.array([3, 4, 5, 6])
common_values = np.intersect1d(array1, array2)
print("Common values between two arrays:", common_values)


Common values between two arrays: [3 4]


In [6]:
# Ignore all numpy warnings

np.seterr(all='ignore')

# Example to trigger a warning
array_warning = np.array([0])
print(1 / array_warning)


[inf]


In [7]:
# Swap two rows in a 2D numpy array

array_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
array_2d[[0, 1]] = array_2d[[1, 0]]
print("Array after swapping rows 0 and 1:\n", array_2d)


Array after swapping rows 0 and 1:
 [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [8]:
# Get the dates of yesterday, today and tomorrow

today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-08-02
Today: 2024-08-03
Tomorrow: 2024-08-04


In [9]:
# Get all dates in August 2023

dates_august_2023 = np.arange('2023-08', '2023-09', dtype='datetime64[D]')
print("Dates in August 2023:\n", dates_august_2023)


Dates in August 2023:
 ['2023-08-01' '2023-08-02' '2023-08-03' '2023-08-04' '2023-08-05'
 '2023-08-06' '2023-08-07' '2023-08-08' '2023-08-09' '2023-08-10'
 '2023-08-11' '2023-08-12' '2023-08-13' '2023-08-14' '2023-08-15'
 '2023-08-16' '2023-08-17' '2023-08-18' '2023-08-19' '2023-08-20'
 '2023-08-21' '2023-08-22' '2023-08-23' '2023-08-24' '2023-08-25'
 '2023-08-26' '2023-08-27' '2023-08-28' '2023-08-29' '2023-08-30'
 '2023-08-31']


In [10]:
# Extract the integer part of a random array

random_array = np.random.random(5) * 10
print("Random array:", random_array)

# Method 1: Using np.floor

integers_floor = np.floor(random_array)
print("Integer part using np.floor:", integers_floor)

# Method 2: Using np.ceil minus 1

integers_ceil_minus_1 = np.ceil(random_array) - 1
print("Integer part using np.ceil minus 1:", integers_ceil_minus_1)

# Method 3: Using np.trunc

integers_trunc = np.trunc(random_array)
print("Integer part using np.trunc:", integers_trunc)

# Method 4: Casting the array to int using .astype(int)

integers_astype = random_array.astype(int)
print("Integer part using .astype(int):", integers_astype)

# Method 5: Using array indexing

integers_indexing = random_array // 1
print("Integer part using array indexing:", integers_indexing)


Random array: [7.56215044 3.63941073 2.01066765 4.98554679 3.14314895]
Integer part using np.floor: [7. 3. 2. 4. 3.]
Integer part using np.ceil minus 1: [7. 3. 2. 4. 3.]
Integer part using np.trunc: [7. 3. 2. 4. 3.]
Integer part using .astype(int): [7 3 2 4 3]
Integer part using array indexing: [7. 3. 2. 4. 3.]


In [11]:
# Find the closest value to a given scalar in an array

array_values = np.random.random(10) * 10
scalar_value = 5.5
closest_value = array_values[np.abs(array_values - scalar_value).argmin()]
print("Array values:", array_values)
print("Closest value to", scalar_value, ":", closest_value)


Array values: [7.77896899 3.06495656 1.83400604 1.03091955 3.49678516 6.32378214
 6.12229582 2.27547329 7.59786703 7.96195674]
Closest value to 5.5 : 6.122295821476017


In [12]:
# Enumerate over a numpy array using np.ndenumerate

array_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
for index, value in np.ndenumerate(array_2d):
    print("Index:", index, "Value:", value)


Index: (0, 0) Value: 0
Index: (0, 1) Value: 1
Index: (0, 2) Value: 2
Index: (1, 0) Value: 3
Index: (1, 1) Value: 4
Index: (1, 2) Value: 5
Index: (2, 0) Value: 6
Index: (2, 1) Value: 7
Index: (2, 2) Value: 8


In [13]:
# Randomly place p elements in a 2D array

array_2d = np.zeros((5, 5))
p = 5
indices = np.random.choice(array_2d.size, p, replace=False)
np.put(array_2d, indices, np.random.random(p))
print("2D array with random elements placed:\n", array_2d)


2D array with random elements placed:
 [[0.         0.         0.         0.31127141 0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.64216403 0.16973057 0.         0.        ]
 [0.         0.40357828 0.         0.         0.03384369]
 [0.         0.         0.         0.         0.        ]]


In [14]:
# Find the nearest value to a given scalar in an array

array_values = np.random.random(10) * 10
scalar_value = 5.5
nearest_value = array_values[np.abs(array_values - scalar_value).argmin()]
print("Array values:", array_values)
print("Nearest value to", scalar_value, ":", nearest_value)


Array values: [6.65827251 7.49082813 6.09328133 1.14542918 4.39527337 0.04242662
 4.89051776 8.10305036 9.91470785 5.10952393]
Nearest value to 5.5 : 5.109523928969027


In [15]:
# Get the index of the maximum value along the last axis

array_4d = np.random.random((3, 4, 5, 6))
last_axis_index = np.argmax(array_4d, axis=-1)
print("Index of maximum value along the last axis:\n", last_axis_index)


Index of maximum value along the last axis:
 [[[1 5 1 1 2]
  [2 2 4 2 3]
  [0 4 0 4 0]
  [0 5 2 0 1]]

 [[2 3 2 3 2]
  [1 5 2 5 1]
  [0 2 4 1 0]
  [3 2 3 3 4]]

 [[2 5 4 1 5]
  [1 0 3 0 4]
  [3 1 4 5 4]
  [0 5 5 5 2]]]


In [16]:
# Sample a path using equidistant samples

X = np.linspace(0, 10, 50)
Y = np.sin(X)
distance = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumulative_distance = np.insert(np.cumsum(distance), 0, 0)
equidistant_samples = np.linspace(0, cumulative_distance[-1], 10)
sampled_points_X = np.interp(equidistant_samples, cumulative_distance, X)
sampled_points_Y = np.interp(equidistant_samples, cumulative_distance, Y)
print("Sampled points along the path:\n", np.vstack((sampled_points_X, sampled_points_Y)).T)


Sampled points along the path:
 [[ 0.          0.        ]
 [ 1.04464858  0.862811  ]
 [ 2.3227204   0.72684549]
 [ 3.3292746  -0.18563532]
 [ 4.4322925  -0.95701871]
 [ 5.6756512  -0.5689128 ]
 [ 6.66177484  0.36793081]
 [ 7.83357915  0.99486774]
 [ 9.01651772  0.39591304]
 [10.         -0.54402111]]
