In [18]:
# Exercise: Advanced Operations in NumPy

import numpy as np

# Generate a 5x5 matrix with random integers ranging from 1 to 100
data = np.array(np.random.randint(1, 100, size=25), dtype=float).reshape(5, 5)
print("Original data matrix:\n", data)


Original data matrix:
 [[62. 44. 59. 92. 24.]
 [48. 26. 59. 65. 83.]
 [38. 51. 17. 86. 27.]
 [19. 52.  4. 29. 87.]
 [62. 94. 44. 51. 91.]]


In [19]:
# Swap the second and fourth rows of the data matrix

data[[1, 3]] = data[[3, 1]]
print("Data matrix after swapping second and fourth rows:\n", data)


Data matrix after swapping second and fourth rows:
 [[62. 44. 59. 92. 24.]
 [19. 52.  4. 29. 87.]
 [38. 51. 17. 86. 27.]
 [48. 26. 59. 65. 83.]
 [62. 94. 44. 51. 91.]]


In [20]:
# Normalize all elements in the data matrix

normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized data matrix:\n", normalized_data)


Normalized data matrix:
 [[0.64444444 0.44444444 0.61111111 0.97777778 0.22222222]
 [0.16666667 0.53333333 0.         0.27777778 0.92222222]
 [0.37777778 0.52222222 0.14444444 0.91111111 0.25555556]
 [0.48888889 0.24444444 0.61111111 0.67777778 0.87777778]
 [0.64444444 1.         0.44444444 0.52222222 0.96666667]]


In [21]:
# Z-score normalization

z_score_data = (data - np.mean(data)) / np.std(data)
print("Z-score normalized data matrix:\n", z_score_data)


Z-score normalized data matrix:
 [[ 0.37015157 -0.33564591  0.25251865  1.5464807  -1.11986533]
 [-1.31592019 -0.02195814 -1.90408475 -0.92381048  1.35042584]
 [-0.57091174 -0.06116911 -1.39434213  1.31121487 -1.00223242]
 [-0.17880203 -1.04144339  0.25251865  0.48778448  1.19358196]
 [ 0.37015157  1.62490264 -0.33564591 -0.06116911  1.50726972]]


In [22]:
# Reshape the data matrix into a vector and split into five equal-sized sub-arrays

data_vector = np.ravel(data)
sub_arrays = np.array_split(data_vector, 5)
print("Sub-arrays:\n", sub_arrays)


Sub-arrays:
 [array([62., 44., 59., 92., 24.]), array([19., 52.,  4., 29., 87.]), array([38., 51., 17., 86., 27.]), array([48., 26., 59., 65., 83.]), array([62., 94., 44., 51., 91.])]


In [23]:
# Create two vectors of size 5

vector1 = np.array([3, 5, 6, 7, 8])
vector2 = np.array([2, 4, 6, 8, 10])

# Compute the dot product

dot_product = np.dot(vector1, vector2)
print("Dot product of the two vectors:", dot_product)


Dot product of the two vectors: 198


In [24]:
# Create another 3x3 matrix with any values

data2 = np.random.randint(1, 100, size=(3, 3))

# Perform matrix multiplication with the first 3x3 part of `data`

matrix_multiplication_result = np.dot(data[:3, :3], data2)
print("Result of matrix multiplication:\n", matrix_multiplication_result)


Result of matrix multiplication:
 [[ 6091.  6734. 10661.]
 [ 2984.  1681.  2602.]
 [ 4005.  3266.  5175.]]


In [25]:
# Create a 3x3 identity matrix, multiply it with 2 and compute its inverse

identity_matrix = np.eye(3) * 2
inverse_matrix = np.linalg.inv(identity_matrix)
print("Inverse of the scaled identity matrix:\n", inverse_matrix)


Inverse of the scaled identity matrix:
 [[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [26]:
# Compute the eigenvalues and eigenvectors for the first 3x3 part of the data matrix

eigenvalues, eigenvectors = np.linalg.eig(data[:3, :3])
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [112.29320915  -8.20028179  26.90707264]
Eigenvectors:
 [[-0.8243555  -0.69497901  0.79903482]
 [-0.29195099  0.17297165 -0.60066427]
 [-0.48497694  0.69791474 -0.02730921]]


In [27]:
# Step 9: Replace random 5 elements with np.nan

indices = np.random.choice(data.size, 5, replace=False)
data_flat = data.flatten()
data_flat[indices] = np.nan
data_with_nan = data_flat.reshape(5, 5)
print("Data matrix with NaNs:\n", data_with_nan)

# Find the indices of the missing values

nan_indices = np.argwhere(np.isnan(data_with_nan))
print("Indices of missing values:\n", nan_indices)

Data matrix with NaNs:
 [[62. nan 59. 92. 24.]
 [19. nan  4. 29. 87.]
 [38. 51. nan nan nan]
 [48. 26. 59. 65. 83.]
 [62. 94. 44. 51. 91.]]
Indices of missing values:
 [[0 1]
 [1 1]
 [2 2]
 [2 3]
 [2 4]]


In [28]:
# Step 10: Replace the missing values with the mean of the matrix

mean_value = np.nanmean(data_with_nan)
data_filled = np.where(np.isnan(data_with_nan), mean_value, data_with_nan)
print("Data matrix with missing values replaced by the mean:\n", data_filled)

Data matrix with missing values replaced by the mean:
 [[62.  54.4 59.  92.  24. ]
 [19.  54.4  4.  29.  87. ]
 [38.  51.  54.4 54.4 54.4]
 [48.  26.  59.  65.  83. ]
 [62.  94.  44.  51.  91. ]]
